joint_names: [left_wam/base_yaw_joint, left_wam/shoulder_pitch_joint, left_wam/shoulder_yaw_joint, left_wam/elbow_pitch_joint, left_wam/wrist_yaw_joint, left_wam/wrist_pitch_joint, left_wam/palm_yaw_joint]

left_wam/base_yaw_joint:
   joint: "left_wam/base_yaw_joint"
   goal_reached_threshold: 0.01
   pid:
     p: 900
     i: 2.5
     d: 10.0
     i_clamp: 2

left_wam/shoulder_pitch_joint:
  joint: left_wam/shoulder_pitch_joint
  goal_reached_threshold: 0.01
  pid:
    p: 2500
    i: 5.0
    d: 20.0
    i_clamp: 2.5

left_wam/shoulder_yaw_joint:
  joint: left_wam/shoulder_yaw_joint
  goal_reached_threshold: 0.01
  pid:
    p: 600
    i: 2.0
    d: 5.0
    i_clamp: 1.0

left_wam/elbow_pitch_joint:
  joint: left_wam/elbow_pitch_joint
  goal_reached_threshold: 0.01
  pid:
    p: 500
    i: 0.5
    d: 2.0
    i_clamp: 0.5

left_wam/wrist_yaw_joint:
  joint: left_wam/wrist_yaw_joint
  goal_reached_threshold: 0.01
  pid:
    p: 50
    i: 0.5
    d: 0.5
    i_clamp: 0.0

left_wam/wrist_pitch_joint:
  joint: left_wam/wrist_pitch_joint
  goal_reached_threshold: 0.01
  pid:
    p: 50
    i: 0.5
    d: 0.5
    i_clamp: 0.0

left_wam/palm_yaw_joint:
  joint: left_wam/palm_yaw_joint
  goal_reached_threshold: 0.01
  pid:
    p: 8
    i: 0.1
    d: 0.05
    i_clamp: 0.0
